title: "BitLancaster"
tagline: "BitDevs is a community for those interested in discussing and participating in the research and development of bitcoin along with following the news surrounding bitcoin."

menu:
  - { name: "About", url: "/about" }
  - { name: "Events", url: "/events" }
  - { name: "Blog", url: "/blog" }
  - {
      name: "Meetup",
      url: "https://www.meetup.com/lancaster-bitcoin-meetup/",
      external: true,
    }
  - { name: "Cities", url: "/cities" }
